### ISSUE TITLE
Crash with latest version (XWalkActivity)

### ISSUE THREAD

**Issue by m1ga** [UniversalAvenue/TiCrosswalk#14]
Using crosswalk 1.3.0, SDK 5.0.2, Android 5.0.2 (Nexus 4):
```xml
<WebView id="www" platform="android" module="com.universalavenue.ticrosswalk" />
```
```
11-20 15:49:31.731: D/XWalkLib(20179): Init embedded mode
11-20 15:49:31.732: D/XWalkLib(20179): lib version, api:5, min api:5
11-20 15:49:31.732: D/XWalkLib(20179): app version, api:5, min api:5
11-20 15:49:31.760: E/art(20179): No implementation found for boolean org.xwalk.core.internal.XWalkViewDelegate.nativeIsLibraryBuiltForIA() (tried Java_org_xwalk_core_internal_XWalkViewDelegate_nativeIsLibraryBuiltForIA and Java_org_xwalk_core_internal_XWalkViewDelegate_nativeIsLibraryBuiltForIA__)
11-20 15:49:31.761: D/XWalkLib(20179): Failed to load native library
11-20 15:49:31.761: D/AndroidRuntime(20179): Shutting down VM
11-20 15:49:31.762: E/AndroidRuntime(20179): FATAL EXCEPTION: main
11-20 15:49:31.762: E/AndroidRuntime(20179): Process: com.x.app, PID: 20179
11-20 15:49:31.762: E/AndroidRuntime(20179): junit.framework.AssertionFailedError: Please have your activity extend XWalkActivity for shared mode
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at junit.framework.Assert.fail(Assert.java:50)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at org.xwalk.core.XWalkCoreWrapper.initEmbeddedMode(XWalkCoreWrapper.java:189)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at org.xwalk.core.XWalkPreferences.reflectionInit(XWalkPreferences.java:207)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at org.xwalk.core.XWalkPreferences.setValue(XWalkPreferences.java:97)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at com.universalavenue.ticrosswalk.TiCrosswalkModule.onAppCreate(TiCrosswalkModule.java:47)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at com.x.app.AppApplication.onCreate(AppApplication.java:101)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at android.os.Looper.loop(Looper.java:135)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at java.lang.reflect.Method.invoke(Native Method)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-20 15:49:31.762: E/AndroidRuntime(20179): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by mrlundis** [comment]
Hello @m1ga! Try adding the following to your tiapp.xml inside the `<android>` tags:
```xml
  <abi>armeabi-v7a</abi>
```

**Comment by m1ga** [comment]
working fine. thanks
