### ISSUE TITLE
App crashed in android

### ISSUE THREAD

**Issue by abada** [UniversalAvenue/TiCrosswalk#23]
```
Operating System
  Name                        = Mac OS X
  Version                     = 10.11.6
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 8589934592

Node.js
  Node.js Version             = 4.2.3
  npm Version                 = 2.14.7

Titanium CLI
  CLI Version                 = 5.0.9

Titanium SDK
  SDK Version                 = 5.4.0.GA
  SDK Path                    = /Users/abdellatifhenno/Library/Application Support/Titanium/mobilesdk/osx/5.4.0.GA
  Target Platform             = android
```

```
[ERROR] art: No implementation found for boolean org.xwalk.core.internal.XWalkViewDelegate.nativeIsLibraryBuiltForIA() (tried Java_org_xwalk_core_internal_XWalkViewDelegate_nativeIsLibraryBuiltForIA and Java_org_xwalk_core_internal_XWalkViewDelegate_nativeIsLibraryBuiltForIA__)
[ERROR] AndroidRuntime: FATAL EXCEPTION: main
[ERROR] AndroidRuntime: Process: com.emoney.sallacpapp, PID: 31786
[ERROR] AndroidRuntime: junit.framework.AssertionFailedError: Please have your activity extend XWalkActivity for shared mode
[ERROR] AndroidRuntime: 	at junit.framework.Assert.fail(Assert.java:50)
[ERROR] AndroidRuntime: 	at org.xwalk.core.XWalkCoreWrapper.initEmbeddedMode(XWalkCoreWrapper.java:189)
[ERROR] AndroidRuntime: 	at org.xwalk.core.XWalkPreferences.reflectionInit(XWalkPreferences.java:207)
[ERROR] AndroidRuntime: 	at org.xwalk.core.XWalkPreferences.setValue(XWalkPreferences.java:97)
[ERROR] AndroidRuntime: 	at com.universalavenue.ticrosswalk.TiCrosswalkModule.onAppCreate(TiCrosswalkModule.java:47)
[ERROR] AndroidRuntime: 	at com.emoney.sallacpapp.Application.onCreate(Application.java:143)
[ERROR] AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1030)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5273)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:178)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
[ERROR] AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
[ERROR] AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6102)
[ERROR] AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
[ERROR] D/[MirrorLinkServer]c(31838): Processing Application::com.htc.music
[ERROR] I/[MirrorLinkServer]c(31838): Getting Application List Alone --Secondary Boot Process
[ERROR] I/[MirrorLinkServer]c(31838): Adding to ML Application List in filterMirrorlinkApps::com.htc.music
[ERROR] D/[MirrorLinkServer]c(31838): Processing Application::com.htc.contacts
[ERROR] I/[MirrorLinkServer]c(31838): Getting Application List Alone --Secondary Boot Process
[ERROR] I/[MirrorLinkServer]c(31838): Adding to ML Application List in filterMirrorlinkApps::com.htc.contacts
[ERROR] D/[MirrorLinkServer]c(31838): Processing Application::com.android.phone
[ERROR] D/[MirrorLinkServer]c(31838): com.android.phone is blacklisted.
[ERROR] I/[MirrorLinkServer]c(31838): appListReady()
[ERROR] I/[MirrorLinkServer]c(31838): Notified all other locked threads to execute
[ERROR] I/[MirrorLinkServer]c(31838): Lock notified
[ERROR] I/[MirrorLinkServer]c(31838): onApplicationUpdationCompleted, sending broadcast
[ERROR] I/[MirrorLinkServer]MirrorLinkServer(31838): Broadcast Received::Intent { act=com.htc.HTCMirrorLinkServer.PACKAGE_UPDATE_COMPLETED }
[ERROR] D/[MirrorLinkServer]MirrorLinkServer(31838): ML_PACKAGE_UPDATE_COMPLETED intent received
[ERROR] D/[MirrorLinkServer]MirrorLinkServer(31838): Counter : 0
[ERROR] I/[MirrorLinkServer]MirrorLinkConnectionReceiver(31838): checkAndStopMLSession
[ERROR] I/[MirrorLinkServer]MirrorLinkConnectionReceiver(31838): Stopping Service
```

**Comment by abada** [comment]
Solved ! 

https://github.com/UniversalAvenue/TiCrosswalk/issues/14
